config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  get 'fridge_contents', to: 'fridges#show'
  # resources :fridges, only: [:show] do
  #   post 'add_item/:item_id', to: 'fridges#add_item', as: 'add_item'
  #   post 'delete_item/:item_id', to: 'fridges#delete_item', as: 'delete_item'
  # end

  resources :fridges do
    post 'increment_item', on: :collection  # if no specific fridge ID is required
    post 'delete_item', on: :collection
    post '/submit-form', to: 'forms#submit_form'
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fridges_controller.rb
class FridgesController < ApplicationController
    before_action :set_fridge_contents, only: [:show, :increment_item, :delete_item]

    def show
    end

    def increment_item
        #item to add is the index
        index = params[:item_id].to_i
        split_arr = session[:fridge_contents][index].split
        num = (split_arr[0].to_i) + 1
        new_item = num.to_s + " " + split_arr[1..-1].join(' ')
        session[:fridge_contents][index] = new_item
        redirect_to fridges_path  # Redirect back to the show page
    end

    def add_item
        #item to add is the index
        item = "1" + params[:item_id].to_s
        session[:fridge_contents] << item unless session[:fridge_contents].include?(item)
        redirect_to fridges_path  # Redirect back to the show page
    end

    def delete_item
        #item to add is the index
        index = params[:item_id].to_i
        split_arr = session[:fridge_contents][index].split
        num = (split_arr[0].to_i) - 1
        new_item = num.to_s + " " + split_arr[1..-1].join(' ')
        session[:fridge_contents][index] = new_item
        redirect_to fridges_path  # Redirect back to the show page
    end

    def submit_form
        # Here you process the input data
        item_info = params[:info].to_s
        # You might want to redirect or render something here
        add_item(@input_data)
      end


    def set_fridge_contents
        # This could be fetching from a database in a real app
        session[:fridge_contents] ||= ['2 Onion', '1 orange', '3 Milk']
        @fridge_contents = session[:fridge_contents]
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fridges_helper.rb
module FridgesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/fridges/show.html.erb
<div class = "header">
    <h1>Fridge Contents</h1>
</div>

<div class = "contents">
    <ul>
       <% @fridge_contents.each_with_index do |item, index| %>
       <div class="list_items">
            <li>
                <%= image_tag('circle.png') %>
                <%= item %>
                <%= button_to 'Add', increment_item_fridges_path(item_id: index), method: :post %>
                <%= button_to 'Delete',delete_item_fridges_path(item_id: index), method: :post %>
            </li>
        </div>
        <% end %>
    </ul>
</div>

<script>
function openPopup() {
    var myWindow = window.open("", "MsgWindow", "width=200,height=100");
    myWindow.document.write("<h1>Input your ingredient:</h1>");
    myWindow.document.write('<form action="/submit-form" method="post"><input type="text" name="info" placeholder="Enter ingredient"><input type="submit" value="Submit"></form>');
}
</script>


<div class = "buttons">
    <button onclick="openPopup()"> Add Fridge Items </button>
    <button type="button" id="current_recipies">Generate New Recipies</button>
</div>

app/views/home/index.html.erb
<!-- <h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
-->

<div class = "header">
    <h1>Home</h1>
    <h2>Popular Recipes</h2>
</div>

<div class = "recipies">
    <%= image_tag('recipe1.jpg') %>
    <%= image_tag('recipe2.jpg') %>
    <%= image_tag('recipe3.jpg') %>
</div>

<div class = "buttons">
    <button type="button" id="current_recipies">Current Recipies</button>
    <%= link_to 'Fridge Contents', fridge_contents_path, class: 'btn', id: 'fridge_contents' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FridgeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: 'all', "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'fridges', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>